// Code generated by MockGen. DO NOT EDIT.
// Source: httpUser.go
//
// Generated by this command:
//
//	mockgen -source=httpUser.go -destination=httpUser_mock.go -package=delivery UserRepoInterface
//

// Package delivery is a generated GoMock package.
package delivery

import (
	session "redditclone/pkg/session"
	user "redditclone/pkg/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepoInterface is a mock of UserRepoInterface interface.
type MockUserRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoInterfaceMockRecorder
	isgomock struct{}
}

// MockUserRepoInterfaceMockRecorder is the mock recorder for MockUserRepoInterface.
type MockUserRepoInterfaceMockRecorder struct {
	mock *MockUserRepoInterface
}

// NewMockUserRepoInterface creates a new mock instance.
func NewMockUserRepoInterface(ctrl *gomock.Controller) *MockUserRepoInterface {
	mock := &MockUserRepoInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepoInterface) EXPECT() *MockUserRepoInterfaceMockRecorder {
	return m.recorder
}

// CheckUser mocks base method.
func (m *MockUserRepoInterface) CheckUser(arg0, arg1 string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUser", arg0, arg1)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUser indicates an expected call of CheckUser.
func (mr *MockUserRepoInterfaceMockRecorder) CheckUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUser", reflect.TypeOf((*MockUserRepoInterface)(nil).CheckUser), arg0, arg1)
}

// Create mocks base method.
func (m *MockUserRepoInterface) Create(arg0, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepoInterfaceMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepoInterface)(nil).Create), arg0, arg1)
}

// MockSessManagerInterface is a mock of SessManagerInterface interface.
type MockSessManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSessManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockSessManagerInterfaceMockRecorder is the mock recorder for MockSessManagerInterface.
type MockSessManagerInterfaceMockRecorder struct {
	mock *MockSessManagerInterface
}

// NewMockSessManagerInterface creates a new mock instance.
func NewMockSessManagerInterface(ctrl *gomock.Controller) *MockSessManagerInterface {
	mock := &MockSessManagerInterface{ctrl: ctrl}
	mock.recorder = &MockSessManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessManagerInterface) EXPECT() *MockSessManagerInterfaceMockRecorder {
	return m.recorder
}

// CreateSess mocks base method.
func (m *MockSessManagerInterface) CreateSess(arg0 *session.Session) (*session.SessionToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSess", arg0)
	ret0, _ := ret[0].(*session.SessionToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSess indicates an expected call of CreateSess.
func (mr *MockSessManagerInterfaceMockRecorder) CreateSess(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSess", reflect.TypeOf((*MockSessManagerInterface)(nil).CreateSess), arg0)
}
