// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -destination=abstract_layer_mock.go -package=repo IMongoDatabase
//

// Package repo is a generated GoMock package.
package repo

import (
	context "context"
	reflect "reflect"

	options "go.mongodb.org/mongo-driver/v2/mongo/options"
	gomock "go.uber.org/mock/gomock"
)

// MockIMongoDatabase is a mock of IMongoDatabase interface.
type MockIMongoDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockIMongoDatabaseMockRecorder
	isgomock struct{}
}

// MockIMongoDatabaseMockRecorder is the mock recorder for MockIMongoDatabase.
type MockIMongoDatabaseMockRecorder struct {
	mock *MockIMongoDatabase
}

// NewMockIMongoDatabase creates a new mock instance.
func NewMockIMongoDatabase(ctrl *gomock.Controller) *MockIMongoDatabase {
	mock := &MockIMongoDatabase{ctrl: ctrl}
	mock.recorder = &MockIMongoDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMongoDatabase) EXPECT() *MockIMongoDatabaseMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockIMongoDatabase) Collection(name string) IMongoCollection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection", name)
	ret0, _ := ret[0].(IMongoCollection)
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockIMongoDatabaseMockRecorder) Collection(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockIMongoDatabase)(nil).Collection), name)
}

// MockIMongoCollection is a mock of IMongoCollection interface.
type MockIMongoCollection struct {
	ctrl     *gomock.Controller
	recorder *MockIMongoCollectionMockRecorder
	isgomock struct{}
}

// MockIMongoCollectionMockRecorder is the mock recorder for MockIMongoCollection.
type MockIMongoCollectionMockRecorder struct {
	mock *MockIMongoCollection
}

// NewMockIMongoCollection creates a new mock instance.
func NewMockIMongoCollection(ctrl *gomock.Controller) *MockIMongoCollection {
	mock := &MockIMongoCollection{ctrl: ctrl}
	mock.recorder = &MockIMongoCollectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMongoCollection) EXPECT() *MockIMongoCollectionMockRecorder {
	return m.recorder
}

// DeleteOne mocks base method.
func (m *MockIMongoCollection) DeleteOne(ctx context.Context, filter any, opts ...options.Lister[options.DeleteOneOptions]) (IDeleteResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOne", varargs...)
	ret0, _ := ret[0].(IDeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockIMongoCollectionMockRecorder) DeleteOne(ctx, filter any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockIMongoCollection)(nil).DeleteOne), varargs...)
}

// Find mocks base method.
func (m *MockIMongoCollection) Find(ctx context.Context, filter any, opts ...options.Lister[options.FindOptions]) (IMongoCursor, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(IMongoCursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIMongoCollectionMockRecorder) Find(ctx, filter any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIMongoCollection)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockIMongoCollection) FindOne(ctx context.Context, filter any, opts ...options.Lister[options.FindOneOptions]) IMongoSingleResult {
	m.ctrl.T.Helper()
	varargs := []any{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(IMongoSingleResult)
	return ret0
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIMongoCollectionMockRecorder) FindOne(ctx, filter any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIMongoCollection)(nil).FindOne), varargs...)
}

// FindOneAndUpdate mocks base method.
func (m *MockIMongoCollection) FindOneAndUpdate(ctx context.Context, filter, update any, opts ...options.Lister[options.FindOneAndUpdateOptions]) IMongoSingleResult {
	m.ctrl.T.Helper()
	varargs := []any{ctx, filter, update}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOneAndUpdate", varargs...)
	ret0, _ := ret[0].(IMongoSingleResult)
	return ret0
}

// FindOneAndUpdate indicates an expected call of FindOneAndUpdate.
func (mr *MockIMongoCollectionMockRecorder) FindOneAndUpdate(ctx, filter, update any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, filter, update}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneAndUpdate", reflect.TypeOf((*MockIMongoCollection)(nil).FindOneAndUpdate), varargs...)
}

// InsertOne mocks base method.
func (m *MockIMongoCollection) InsertOne(ctx context.Context, document any, opts ...options.Lister[options.InsertOneOptions]) (IMongoInsertOneResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, document}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertOne", varargs...)
	ret0, _ := ret[0].(IMongoInsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockIMongoCollectionMockRecorder) InsertOne(ctx, document any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, document}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockIMongoCollection)(nil).InsertOne), varargs...)
}

// UpdateByID mocks base method.
func (m *MockIMongoCollection) UpdateByID(ctx context.Context, id, update any, opts ...options.Lister[options.UpdateOneOptions]) (IMongoUpdateResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id, update}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateByID", varargs...)
	ret0, _ := ret[0].(IMongoUpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIMongoCollectionMockRecorder) UpdateByID(ctx, id, update any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id, update}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIMongoCollection)(nil).UpdateByID), varargs...)
}

// MockIMongoSingleResult is a mock of IMongoSingleResult interface.
type MockIMongoSingleResult struct {
	ctrl     *gomock.Controller
	recorder *MockIMongoSingleResultMockRecorder
	isgomock struct{}
}

// MockIMongoSingleResultMockRecorder is the mock recorder for MockIMongoSingleResult.
type MockIMongoSingleResultMockRecorder struct {
	mock *MockIMongoSingleResult
}

// NewMockIMongoSingleResult creates a new mock instance.
func NewMockIMongoSingleResult(ctrl *gomock.Controller) *MockIMongoSingleResult {
	mock := &MockIMongoSingleResult{ctrl: ctrl}
	mock.recorder = &MockIMongoSingleResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMongoSingleResult) EXPECT() *MockIMongoSingleResultMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockIMongoSingleResult) Decode(v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockIMongoSingleResultMockRecorder) Decode(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockIMongoSingleResult)(nil).Decode), v)
}

// Err mocks base method.
func (m *MockIMongoSingleResult) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockIMongoSingleResultMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockIMongoSingleResult)(nil).Err))
}

// MockIMongoUpdateResult is a mock of IMongoUpdateResult interface.
type MockIMongoUpdateResult struct {
	ctrl     *gomock.Controller
	recorder *MockIMongoUpdateResultMockRecorder
	isgomock struct{}
}

// MockIMongoUpdateResultMockRecorder is the mock recorder for MockIMongoUpdateResult.
type MockIMongoUpdateResultMockRecorder struct {
	mock *MockIMongoUpdateResult
}

// NewMockIMongoUpdateResult creates a new mock instance.
func NewMockIMongoUpdateResult(ctrl *gomock.Controller) *MockIMongoUpdateResult {
	mock := &MockIMongoUpdateResult{ctrl: ctrl}
	mock.recorder = &MockIMongoUpdateResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMongoUpdateResult) EXPECT() *MockIMongoUpdateResultMockRecorder {
	return m.recorder
}

// MockIMongoInsertOneResult is a mock of IMongoInsertOneResult interface.
type MockIMongoInsertOneResult struct {
	ctrl     *gomock.Controller
	recorder *MockIMongoInsertOneResultMockRecorder
	isgomock struct{}
}

// MockIMongoInsertOneResultMockRecorder is the mock recorder for MockIMongoInsertOneResult.
type MockIMongoInsertOneResultMockRecorder struct {
	mock *MockIMongoInsertOneResult
}

// NewMockIMongoInsertOneResult creates a new mock instance.
func NewMockIMongoInsertOneResult(ctrl *gomock.Controller) *MockIMongoInsertOneResult {
	mock := &MockIMongoInsertOneResult{ctrl: ctrl}
	mock.recorder = &MockIMongoInsertOneResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMongoInsertOneResult) EXPECT() *MockIMongoInsertOneResultMockRecorder {
	return m.recorder
}

// InsertedId mocks base method.
func (m *MockIMongoInsertOneResult) InsertedId() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertedId")
	ret0, _ := ret[0].(any)
	return ret0
}

// InsertedId indicates an expected call of InsertedId.
func (mr *MockIMongoInsertOneResultMockRecorder) InsertedId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertedId", reflect.TypeOf((*MockIMongoInsertOneResult)(nil).InsertedId))
}

// MockIDeleteResult is a mock of IDeleteResult interface.
type MockIDeleteResult struct {
	ctrl     *gomock.Controller
	recorder *MockIDeleteResultMockRecorder
	isgomock struct{}
}

// MockIDeleteResultMockRecorder is the mock recorder for MockIDeleteResult.
type MockIDeleteResultMockRecorder struct {
	mock *MockIDeleteResult
}

// NewMockIDeleteResult creates a new mock instance.
func NewMockIDeleteResult(ctrl *gomock.Controller) *MockIDeleteResult {
	mock := &MockIDeleteResult{ctrl: ctrl}
	mock.recorder = &MockIDeleteResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeleteResult) EXPECT() *MockIDeleteResultMockRecorder {
	return m.recorder
}

// MockIMongoCursor is a mock of IMongoCursor interface.
type MockIMongoCursor struct {
	ctrl     *gomock.Controller
	recorder *MockIMongoCursorMockRecorder
	isgomock struct{}
}

// MockIMongoCursorMockRecorder is the mock recorder for MockIMongoCursor.
type MockIMongoCursorMockRecorder struct {
	mock *MockIMongoCursor
}

// NewMockIMongoCursor creates a new mock instance.
func NewMockIMongoCursor(ctrl *gomock.Controller) *MockIMongoCursor {
	mock := &MockIMongoCursor{ctrl: ctrl}
	mock.recorder = &MockIMongoCursorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMongoCursor) EXPECT() *MockIMongoCursorMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockIMongoCursor) All(arg0 context.Context, arg1 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// All indicates an expected call of All.
func (mr *MockIMongoCursorMockRecorder) All(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockIMongoCursor)(nil).All), arg0, arg1)
}

// Close mocks base method.
func (m *MockIMongoCursor) Close(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIMongoCursorMockRecorder) Close(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIMongoCursor)(nil).Close), arg0)
}

// Decode mocks base method.
func (m *MockIMongoCursor) Decode(arg0 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockIMongoCursorMockRecorder) Decode(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockIMongoCursor)(nil).Decode), arg0)
}

// Next mocks base method.
func (m *MockIMongoCursor) Next(arg0 context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockIMongoCursorMockRecorder) Next(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockIMongoCursor)(nil).Next), arg0)
}
