// Code generated by MockGen. DO NOT EDIT.
// Source: httpPost.go
//
// Generated by this command:
//
//	mockgen -source=httpPost.go -destination=httpPost_mock.go -package=delivery PostsRepoInterface
//

// Package delivery is a generated GoMock package.
package delivery

import (
	post "redditclone/pkg/post"
	reflect "reflect"

	bson "go.mongodb.org/mongo-driver/v2/bson"
	gomock "go.uber.org/mock/gomock"
)

// MockPostRepoInterface is a mock of PostRepoInterface interface.
type MockPostRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepoInterfaceMockRecorder
	isgomock struct{}
}

// MockPostRepoInterfaceMockRecorder is the mock recorder for MockPostRepoInterface.
type MockPostRepoInterfaceMockRecorder struct {
	mock *MockPostRepoInterface
}

// NewMockPostRepoInterface creates a new mock instance.
func NewMockPostRepoInterface(ctrl *gomock.Controller) *MockPostRepoInterface {
	mock := &MockPostRepoInterface{ctrl: ctrl}
	mock.recorder = &MockPostRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepoInterface) EXPECT() *MockPostRepoInterfaceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockPostRepoInterface) Add(arg0 *post.Post) (*post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0)
	ret0, _ := ret[0].(*post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockPostRepoInterfaceMockRecorder) Add(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockPostRepoInterface)(nil).Add), arg0)
}

// Destroy mocks base method.
func (m *MockPostRepoInterface) Destroy(arg0 bson.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockPostRepoInterfaceMockRecorder) Destroy(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockPostRepoInterface)(nil).Destroy), arg0)
}

// Downvote mocks base method.
func (m *MockPostRepoInterface) Downvote(arg0 bson.ObjectID, arg1 int) (*post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Downvote", arg0, arg1)
	ret0, _ := ret[0].(*post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Downvote indicates an expected call of Downvote.
func (mr *MockPostRepoInterfaceMockRecorder) Downvote(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Downvote", reflect.TypeOf((*MockPostRepoInterface)(nil).Downvote), arg0, arg1)
}

// FindByAuthor mocks base method.
func (m *MockPostRepoInterface) FindByAuthor(arg0 string) ([]*post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAuthor", arg0)
	ret0, _ := ret[0].([]*post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAuthor indicates an expected call of FindByAuthor.
func (mr *MockPostRepoInterfaceMockRecorder) FindByAuthor(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAuthor", reflect.TypeOf((*MockPostRepoInterface)(nil).FindByAuthor), arg0)
}

// FindByCategory mocks base method.
func (m *MockPostRepoInterface) FindByCategory(arg0 string) ([]*post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCategory", arg0)
	ret0, _ := ret[0].([]*post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCategory indicates an expected call of FindByCategory.
func (mr *MockPostRepoInterfaceMockRecorder) FindByCategory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCategory", reflect.TypeOf((*MockPostRepoInterface)(nil).FindByCategory), arg0)
}

// FindByID mocks base method.
func (m *MockPostRepoInterface) FindByID(arg0 bson.ObjectID) (*post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0)
	ret0, _ := ret[0].(*post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPostRepoInterfaceMockRecorder) FindByID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPostRepoInterface)(nil).FindByID), arg0)
}

// GetAll mocks base method.
func (m *MockPostRepoInterface) GetAll() ([]*post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPostRepoInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPostRepoInterface)(nil).GetAll))
}

// Unvote mocks base method.
func (m *MockPostRepoInterface) Unvote(arg0 bson.ObjectID, arg1 int) (*post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unvote", arg0, arg1)
	ret0, _ := ret[0].(*post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unvote indicates an expected call of Unvote.
func (mr *MockPostRepoInterfaceMockRecorder) Unvote(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unvote", reflect.TypeOf((*MockPostRepoInterface)(nil).Unvote), arg0, arg1)
}

// Upvote mocks base method.
func (m *MockPostRepoInterface) Upvote(arg0 bson.ObjectID, arg1 int) (*post.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upvote", arg0, arg1)
	ret0, _ := ret[0].(*post.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upvote indicates an expected call of Upvote.
func (mr *MockPostRepoInterfaceMockRecorder) Upvote(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upvote", reflect.TypeOf((*MockPostRepoInterface)(nil).Upvote), arg0, arg1)
}
